name: Java CI

on: 
  push:
    branches:
      - master

jobs:
  before-test:

    runs-on: ubuntu-18.04

    steps:
    - name: print Hello
      uses: echo "Hello!"
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: cd ./app && java -jar rest.jar
 
  testing:

    runs-on: ubuntu-18.04

    steps:
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      
      
