name: Java CI

on: 
  push:
    branches:
      - master
    

jobs:
  before_testing:
    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: run student application
      run: cd ./app/ $$ java -jar rest.jar

  testing:
     runs-on: [ubuntu-16.04]
     needs: [before_testing]
 
  steps:
