name: JavaCI

on: 
  push:
    branches:
      - master

jobs:
  before-test:

    runs-on: [ubuntu-18.04]

    steps:
    - name: print Hello
      run: echo Hello!
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: 'x64'
  
    - name: run rest.jar for testing
      run: java -jar -Xmx32m app/rest.jar --server.port=8085
    - name: run our application 
      run: mvn -B package --file pom.xml
