name: JavaCI

on: 
  push:
    branches:
      - master

jobs:
  before-test:

    runs-on: [ubuntu-18.04]

    steps:
    - name: print Hello
      run: echo Hello!
    - uses: actions/checkout@latest
    - name: Set up JDK 1.8
      uses: actions/setup-jdk@v1
      with:
        java-version: 1.8
        architecture: 'x64'
  
    - name: run rest.jar for testing
      run: java -cp java app/rest.jar
    - name: run our application 
      run: mvn -B package --file pom.xml
